"""Step 5: HR entry — leave and gate pass.

**HR types a form that has already been signed on paper** (SPEC §5, §6). There
is no approval to route, no entitlement to check and no balance to keep: a
signature block on paper is not a workflow, and Milestone 5 is where routing
one lives.

Two rules from the forms are enforced rather than trusted:

  * **The number of days is what the form says.** `record_leave` requires it and
    **there is no code path that derives it from the range** — a half day, and a
    non-working day inside a range, both mean the count and the span are
    different numbers.
  * **The hours on a gate pass are never typed.** `record_gate_pass` has no
    hours parameter, and the column is generated by the database from the two
    times. The form carries no hours field either; this is the same reflex as
    the guard entry with no field for a time (SPEC §3).

**Neither leave field is filled in from the other.** The applied-for type and
the sheet code are two fields, either may be empty, and the only thing that
connects them is a suggestion the entry screen offers before HR touches it
(SPEC §9 A48). Whatever HR types is what the row records.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from decimal import Decimal

from sqlalchemy import select

from app.models import (
    Employee,
    GatePass,
    GatePassCategory,
    LeaveCode,
    LeaveRecord,
    LeaveType,
    ScreenUser,
)

# Who is at the keyboard on an HR entry screen. The other value is 'guard',
# which is a different person in a different place doing a different thing
# (SPEC §3).
HR = "hr"


@dataclass
class DayLeave:
    """What leave says about one employee on one day, for the sheet."""

    record_id: int
    sheet_code: str | None
    type_code: str | None
    type_label: str | None
    days: Decimal
    part_day: bool


def leave_types(session) -> list[LeaveType]:
    return list(session.scalars(
        select(LeaveType).order_by(LeaveType.sort_order)))


def leave_codes(session) -> list[LeaveCode]:
    return list(session.scalars(select(LeaveCode).order_by(LeaveCode.code)))


def categories(session) -> list[GatePassCategory]:
    return list(session.scalars(
        select(GatePassCategory).order_by(GatePassCategory.sort_order)))


def typists(session) -> list[ScreenUser]:
    """Who may be typing a form. **Rows, and attribution rather than a login**
    — the same table the guard screen picks from, HR's side of it (SPEC §3).

    It lives here rather than on either entry screen because both write through
    this module: leave and gate passes are typed by the same two people, and a
    second screen reaching into the first one's module to find them would make
    the leave screen a dependency of everything typed afterwards.
    """
    return list(session.scalars(
        select(ScreenUser)
        .where(ScreenUser.screen == HR, ScreenUser.active.is_(True))
        .order_by(ScreenUser.sort_order, ScreenUser.code)
    ))


def typist(session, code: str) -> ScreenUser:
    """One of them, by code. An unknown code is refused: every form records who
    typed it (SPEC §5, §6)."""
    row = session.get(ScreenUser, (code or "").strip())
    if row is None or row.screen != HR or not row.active:
        allowed = [user.code for user in typists(session)]
        raise ValueError(
            f"{code!r} is not somebody on the HR list. A form records who "
            f"typed it (SPEC §5, §6). On the list: {allowed}"
        )
    return row


def suggested_code(session, type_code: str | None) -> str | None:
    """What the entry screen offers beside the type (A48).

    A suggestion, not a mapping: four of the seven types have none, and nothing
    downstream reads this — the row records what HR typed.
    """
    if not type_code:
        return None
    row = session.get(LeaveType, type_code.strip().upper())
    return row.suggested_sheet_code if row else None


def record_leave(session, employee: Employee, *, period_from: dt.date,
                 period_to: dt.date, days, date_of_application: dt.date | None,
                 entered_by: str, leave_type_code: str | None = None,
                 sheet_code: str | None = None, reason: str | None = None,
                 note: str | None = None) -> LeaveRecord:
    """One line of leave, as the form has it.

    `days` is required and is stored as given. **Nothing here counts the days
    between two dates**, and adding that would mean changing this signature as
    well as the caller — the same shape as the guard entry that cannot be given
    a time.
    """
    if days is None:
        raise ValueError(
            "the number of days is on the form and is stored as given. It is "
            "never computed from the range: a half day, and a non-working day "
            "inside a range, both mean the count and the span differ (SPEC §6)"
        )
    try:
        days = Decimal(str(days).strip())
    except (ArithmeticError, ValueError):
        raise ValueError(
            f"{days!r} is not a number of days. The form states it — 1, 2, or "
            "0.5 for a half day (SPEC §6)"
        ) from None
    if days.is_nan() or days.is_infinite():
        raise ValueError(f"{days} is not a number of days")
    if days <= 0:
        raise ValueError(f"{days} days is not a number of days")
    if days % Decimal("0.5") != 0:
        raise ValueError(
            f"{days} is not a whole or half day. A half day is stored as 0.5 "
            "(SPEC §9 A15)"
        )
    if period_to < period_from:
        raise ValueError(f"{period_to} is before {period_from}")

    type_code = (leave_type_code or "").strip().upper() or None
    code = (sheet_code or "").strip().upper() or None
    if type_code is None and code is None:
        raise ValueError(
            "a leave record says what it is: the type applied for, the code HR "
            "writes on the sheet, or both. Neither is derived from the other "
            "(SPEC §6)"
        )
    if type_code is not None and session.get(LeaveType, type_code) is None:
        allowed = [row.code for row in leave_types(session)]
        raise ValueError(f"{type_code!r} is not a type on the form. {allowed}")
    if code is not None and session.get(LeaveCode, code) is None:
        allowed = [row.code for row in leave_codes(session)]
        raise ValueError(f"{code!r} is not a code in the sheet legend. {allowed}")
    if not entered_by or not entered_by.strip():
        raise ValueError("a leave record says who entered it")

    row = LeaveRecord(
        employee_id=employee.id,
        leave_type_code=type_code,
        sheet_code=code,
        period_from=period_from,
        period_to=period_to,
        days=days,
        date_of_application=date_of_application,
        reason=(reason or None),
        # Empty until Accounts answers what the payroll codes mean (SPEC §8).
        sql_account_code=None,
        entered_by=entered_by.strip(),
        note=note,
    )
    session.add(row)
    session.flush()
    return row


def record_gate_pass(session, employee: Employee, *, pass_date: dt.date,
                     category_code: str, out_time: dt.time, in_time: dt.time,
                     entered_by: str, reason: str | None = None,
                     destination: str | None = None,
                     note: str | None = None) -> GatePass:
    """One gate pass, as the form has it.

    **There is no hours parameter and there is no department parameter.** The
    hours come from the two times, in the database; the department is not on
    the form at all and the employee's section is looked up (SPEC §5).
    """
    code = (category_code or "").strip().upper()
    if session.get(GatePassCategory, code) is None:
        allowed = [row.code for row in categories(session)]
        raise ValueError(
            f"{code!r} is not one of the four ticks on the gate pass. {allowed}")
    if in_time <= out_time:
        raise ValueError(
            f"in time {in_time} is not after out time {out_time}. The form "
            "carries one date and two times, so a pass begins and ends on the "
            "same day (SPEC §5)"
        )
    if not entered_by or not entered_by.strip():
        raise ValueError("a gate pass says who entered it")

    row = GatePass(
        employee_id=employee.id,
        pass_date=pass_date,
        category_code=code,
        reason=(reason or None),
        destination=(destination or None),
        out_time=out_time,
        in_time=in_time,
        entered_by=entered_by.strip(),
        note=note,
    )
    session.add(row)
    session.flush()
    # The database computed the hours; read them back rather than working them
    # out here, so there is one answer and it is the stored one.
    session.refresh(row)
    return row


def leave_for(session, employee_id: int, day: dt.date) -> DayLeave | None:
    """The leave covering one employee on one day, if any."""
    row = session.scalars(
        select(LeaveRecord)
        .where(
            LeaveRecord.employee_id == employee_id,
            LeaveRecord.period_from <= day,
            LeaveRecord.period_to >= day,
        )
        .order_by(LeaveRecord.id)
        .limit(1)
    ).first()
    if row is None:
        return None
    label = None
    if row.leave_type_code:
        leave_type = session.get(LeaveType, row.leave_type_code)
        label = leave_type.label if leave_type else row.leave_type_code
    return DayLeave(
        record_id=row.id,
        sheet_code=row.sheet_code,
        type_code=row.leave_type_code,
        type_label=label,
        days=row.days,
        part_day=row.days % 1 != 0,
    )


def leave_by_day(session, start: dt.date, end: dt.date) -> dict:
    """Every day of leave in a period, keyed by (employee, date).

    Built by walking each record's own from and to dates. **The number of days
    on the record is not touched**: a three-day range with 2.5 days on it marks
    three cells and still counts 2.5 days, because the count and the span are
    different facts (SPEC §6).
    """
    out: dict[tuple[int, dt.date], DayLeave] = {}
    rows = session.scalars(
        select(LeaveRecord)
        .where(LeaveRecord.period_from <= end, LeaveRecord.period_to >= start)
        .order_by(LeaveRecord.id)
    ).all()
    labels = {row.code: row.label for row in leave_types(session)}
    for row in rows:
        day = max(row.period_from, start)
        last = min(row.period_to, end)
        while day <= last:
            out.setdefault((row.employee_id, day), DayLeave(
                record_id=row.id,
                sheet_code=row.sheet_code,
                type_code=row.leave_type_code,
                type_label=labels.get(row.leave_type_code),
                days=row.days,
                part_day=row.days % 1 != 0,
            ))
            day += dt.timedelta(days=1)
    return out


def leave_records(session, employee_id: int | None, start: dt.date,
                  end: dt.date) -> list[LeaveRecord]:
    query = (
        select(LeaveRecord)
        .where(LeaveRecord.period_from <= end, LeaveRecord.period_to >= start)
        .order_by(LeaveRecord.period_from, LeaveRecord.id)
    )
    if employee_id is not None:
        query = query.where(LeaveRecord.employee_id == employee_id)
    return list(session.scalars(query))


def gate_passes(session, employee_id: int | None, start: dt.date,
                end: dt.date) -> list[GatePass]:
    query = (
        select(GatePass)
        .where(GatePass.pass_date >= start, GatePass.pass_date <= end)
        .order_by(GatePass.pass_date, GatePass.id)
    )
    if employee_id is not None:
        query = query.where(GatePass.employee_id == employee_id)
    return list(session.scalars(query))
