#!/usr/bin/env python3
"""Write fixtures/employees_punch_demo.xlsx — a list whose PINs match the
punches actually in the database, so the sheet can be seen with data on it.

**This is a demonstration list, not HR's.** It is shaped like HR's — the same
header row, the same footer under the data, the same column letters as the
sample — but the PINs are chosen to line up with what has been captured:

    1            the real device, PIN 1, punches on 2026-08-20
    0090, 0657   the simulator's own batch on 2026-08-18
    1627
    0001-0050    the simulator's shift-worth batch on 2026-08-18

**Most of those PINs start with a zero, which the device refuses** (SPEC §2,
§10) — they exist because the simulator sends shapes the hardware cannot, on
purpose. Importing this list therefore needs `--accept-leading-zero-pins`, and
that is the point: the flag is what makes "these PINs can never come off this
device" a sentence somebody typed rather than a silence.

Four employees are given no Device ID at all, so the sheet has empty rows in it
as well as full ones.

    uv run python tools/make_punch_demo_fixture.py
"""

from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font

OUT = Path("fixtures/employees_punch_demo.xlsx")

HEADERS = [
    (1, "No."), (2, "Emp No."), (4, "Employee Name"), (5, "Section"),
    (6, "Role"), (7, "Shift Group"), (9, "Joined"), (10, "Left"),
    (11, "Device ID"),
]

SECTIONS = ["PACK ASSY", "QC", "MAINT", "PROJECT DOOR", "WAREHOUSE"]
ROLES = ["Production Assistant", "QA/QC", "Charge Hand", "Assistant Supervisor"]

# Names have to be distinct across the whole list. Two employees called the
# same thing on a sheet somebody reads by eye is a mistake waiting to be made,
# and it is the sort of thing a generator produces by accident when it pairs a
# short list of firsts with a short list of lasts.
FIRST = [
    "Ah Meng", "Siti", "Ravi", "Wei Sheng", "Nurul", "Chee Keong", "Mei Ling",
    "Aung", "Chandran", "Zubaidah", "Kai Xin", "Hafiz", "Su Lin", "Arun",
    "Boon Hui", "Farah", "Jia Hui", "Kumar", "Lina", "Tze Yang", "Poh Choo",
    "Zainal", "Vimala", "Beng Huat", "Rosnah", "Sanjay", "Yoke Lan", "Idris",
    "Kalai", "Cheng Hoe", "Norhayati", "Prakash", "Swee Lian", "Faizal",
    "Devi", "Kok Wai", "Anisah", "Ganesan", "Peik Ying", "Rahim",
]
LAST = [
    "Tan", "binti Rahman", "a/l Subramaniam", "Lim", "Wong", "Ko Min",
    "a/l Muthu", "binti Osman", "Chong", "Ismail", "Lee", "Ng", "a/p Raju",
    "bin Salleh", "Cheah", "Yap", "Loh", "a/l Nathan", "binti Yusof", "Teoh",
]


def name_for(index: int) -> str:
    """A distinct name per index.

    The two lists are coprime in length (40 and 20 would repeat every 40), so
    the last name advances on its own cycle and the pair only repeats after
    len(FIRST) × len(LAST) names. The generator checks for duplicates before it
    writes, rather than trusting that.
    """
    return f"{FIRST[index % len(FIRST)]} {LAST[(index // len(FIRST)) % len(LAST)]}"


def rows() -> list[tuple]:
    out: list[tuple] = []

    # The real device's own test enrollment. PIN 1, exactly as it punches.
    # An ordinary name, like everybody else on the list. This row is only
    # special because its PIN is the one the real device punches with.
    out.append(("9001", "Yeoh Kim Seng", "MAINT", "Charge Hand",
                "DAY-PROD", "01/08/2026", "", "1"))

    # The simulator's named punches on 2026-08-18.
    for number, pin, name, section, role, group in (
        ("0090", "0090", "Lim Wei Sheng", "PACK ASSY", "Production Assistant",
         "DAY-PROD"),
        ("0657", "0657", "Tan Chee Keong", "QC", "QA/QC", "DAY-PROD"),
        ("1627", "1627", "Aung Ko Min", "MAINT", "Production Assistant",
         "NIGHT-PROD"),
    ):
        out.append((number, name, section, role, group, "12/03/2018", "", pin))

    # The shift's worth: fifty punches, one each, 07:01 to 07:50.
    for i in range(1, 51):
        out.append((
            f"2{i:03d}", name_for(i), SECTIONS[i % len(SECTIONS)],
            ROLES[i % len(ROLES)],
            "NIGHT-PROD" if i % 7 == 0 else "DAY-PROD",
            "05/01/2020", "", f"{i:04d}",
        ))

    # Four with no Device ID: employed, on the sheet, and nothing attributed to
    # them. An empty row is a real case and the sheet has to show one.
    for offset, (number, group) in enumerate((
        ("3001", "DAY-PROD"), ("3002", "OFFICE"),
        ("3003", "NIGHT-PROD"), ("3004", "DAY-PROD"),
    )):
        out.append((number, name_for(60 + offset), SECTIONS[offset % 5],
                    ROLES[offset % 4], group, "17/09/2021", "", ""))
    return out


def main() -> int:
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Staff List"

    sheet["A1"] = "DEMONSTRATION LIST — PINs match captured punches, not HR's list"
    sheet["A1"].font = Font(bold=True)
    sheet["A2"] = "Generated by tools/make_punch_demo_fixture.py"

    header_row = 4
    for column, text in HEADERS:
        cell = sheet.cell(header_row, column, text)
        cell.font = Font(bold=True)

    data = rows()
    for index, row in enumerate(data):
        excel_row = header_row + 1 + index
        number, name, section, role, group, joined, left, pin = row
        sheet.cell(excel_row, 1, index + 1)
        sheet.cell(excel_row, 2, number)
        sheet.cell(excel_row, 4, name)
        sheet.cell(excel_row, 5, section)
        sheet.cell(excel_row, 6, role)
        sheet.cell(excel_row, 7, group)
        sheet.cell(excel_row, 9, joined)
        sheet.cell(excel_row, 10, left)
        sheet.cell(excel_row, 11, pin)

    names = [row[1] for row in data]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise SystemExit(
            f"the generator produced {len(duplicates)} repeated name(s): "
            f"{duplicates}. A sheet read by eye needs distinct names"
        )

    footer = header_row + 1 + len(data)
    sheet.cell(footer, 2, "TOTAL")
    sheet.cell(footer, 4, f"{len(data)} employees")

    for letter, width in (("A", 6), ("B", 10), ("D", 26), ("E", 16), ("F", 22),
                          ("G", 14), ("I", 12), ("J", 12), ("K", 12)):
        sheet.column_dimensions[letter].width = width

    OUT.parent.mkdir(parents=True, exist_ok=True)
    workbook.save(OUT)
    print(f"wrote {OUT}: {len(data)} employees, header row {header_row}, "
          f"data rows {header_row + 1}-{footer - 1}, footer row {footer}")
    with_pin = sum(1 for r in data if r[7])
    print(f"  {with_pin} carry a Device ID, {len(data) - with_pin} do not")
    print("  most PINs start with a zero — the import needs "
          "--accept-leading-zero-pins (SPEC §2)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
